# the config file must be saved as config.toml
# change the values as required

# port value
Port = 9000

# env (environment) =  { debug | test | release }
# use "release" mode in production
Env = "debug"

# the domain at which app will available
Domain = "https://app-name.herokuapp.com"


# the cors policy, list of supported domains
Cors = ["*"]


# smtp details
[MAIL]

# host address
Host = "smtp.mailtrap.io"

# port
Port = 2525

# Username 
Username = "gdj97f97efjnejf"

# Password
Password = "ejf87f87efefef"

# Sender
Sender = "<no-reply@soe-backend.io>"


# postgres database details
[DB]

# postgres connection string ( dsn -data source name)
Dsn = "postgres://username@password@host:port/dbname"

# postgres max open connections
MaxOpenConns = 25

# postgres max idle connections
MaxIdleConns = 25

# postgres max connection time
MaxIdleTime = "15m"